version: '3.8'

services:
  app:
    build: .
    image: pjundmd
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQL_HOST}:3306/pushop?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_REDIS_HOST: redis
      JWT_SECRET: ${JWT_SECRET}
      NAVER_PASSWORD: ${NAVER_PASSWORD}
      IMP_API_KEY: ${IMP_API_KEY}
      IMP_SECRET_KEY: ${IMP_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_SECRET: ${KAKAO_SECRET}
      NAVER_REDIRECT_URI: ${NAVER_REDIRECT_URI}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped
    cpuset: "0"
    cpu_shares: 512

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - NGINX_SERVER=${NGINX_SERVER}
    restart: unless-stopped
    cpuset: "1"
    cpu_shares: 256

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    cpuset: "1"
    cpu_shares: 256

volumes:
  mysql-data:

