spring:
  mail:
    username: gokorea1214@gmail.com
    password: ${GOOGLE_PASSWORD}
    host: smtp.gmail.com
    port: 587
    # google 587 naver 465
    auth-code-expiration-millis: 1800000 # 30분 = 30 * 60 * 1000
